#TEST PHASE1 AWS PROVISIONING
- hosts: localhost
  name: Provision Stack Aws Centos
  connection: local
  gather_facts: True
  vars:
    cloudformationFile: demopoc2.yml.j2
    provisioner: aws
    stack_name: "centos"
    stack_app: "lab"
    user: "centos"
  vars_files:
    - "keys/private/{{provisioner}}_private.yml"
  roles:
    - distrostack
#TEST PHASE2 APPLYING ROLE BASE

- hosts: tag_Name_centos_lab
  name: Set up instances
  user: centos
  gather_facts: True
  vars:
    provisioner: aws
    stack_name: "demopoc2"
    stack_app: "docker2"
    user: "centos"
  vars_files:
    - "keys/private/{{provisioner}}_private.yml"
  roles:
    - base
