#TEST PHASE1 AWS PROVISIONING
- hosts: localhost
  name: Provision Stack Aws Demo 1
  connection: local
  gather_facts: True
  vars:
    provisioner: aws
  vars_files:
    - "keys/private/{{provisioner}}_private.yml"
  roles:
    - distrostack

#TEST PHASE2 APPLYING ROLE BASE

- hosts: tag_Name_demopoc_docker
  name: Set up instances
  user: ec2-user
  gather_facts: True
  vars:
    provisioner: aws
  vars_files:
    - "keys/private/{{provisioner}}_private.yml"
  roles:
    - base

#TEST PHASE3 DEPLOYING WORDPRESS APP

- hosts: tag_Name_demopoc_docker
  name: Set up instances
  user: ec2-user
  gather_facts: True
  vars:
    provisioner: aws
    distribution: aws
    enviroment: testing
  vars_files:
    - "keys/private/{{provisioner}}_private.yml"
  roles:
    - dockercompose
