- include: "roles/base/tasks/base-{{package_manager}}.yml"

- name: Passwordless sudo
  become: True
  become_user: root
  lineinfile: "dest=/etc/sudoers state=present regexp='^%wheel' line='%wheel ALL=(ALL) NOPASSWD: ALL'"
  when: "{{passwordless_sudo}}"

- name: Restart Services
  include: ../handlers/main.yml
